[tool.poetry]
name = "back-end"
version = "0.1.0"
description = ""
authors = ["Jhonatan-Diniz <jhonatandiniz360@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "^0.115.5"}


[tool.poetry.group.dev.dependencies]
taskipy = "^1.14.1"

[tool.taskipy.tasks]
dev = 'fastapi dev src/api/main.py --port 8000'
run = 'uvicorn src.api.main:app'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
